### ISSUE TITLE
Definir tópicos da apresentação

### ISSUE THREAD

**Issue by rafaeleyng** [codeheaven-io/github-talk#1]

**Comment by marlonbernardes** [comment]
## Geral
- Explicar o que é SCM

## Git Básico
- Uma breve história do Git
- O que é Git?
  - Princípios 
- Git Básico
  - Alguns comandos básicos (ìnit, status, add, commit, log `)
 
## GitHub Básico
- O que é?
- Criando um novo projeto
- Como "Clonar"  um projeto existente
- 

## Git Básico 2
- Mais comandos `branch` sem explicar muito, `push` e `pull`
